=== ndang/wba2_phase2/Phase2/XSD/theme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="themes">
    <xs:complexType>
        <xs:sequence>
             <xs:element name="theme" maxOccurs="unbounded" minOccurs="1">
                 <xs:complexType>
                     <xs:sequence>
                         <xs:element name="allgemeines" minOccurs="1" maxOccurs="1">
                             <xs:complexType>
                                 <xs:sequence>
                                     <xs:element name="theme_titel" maxOccurs="1" minOccurs="1"/>
                                     <xs:element name="genres" minOccurs="1" maxOccurs="1">
                                         <xs:complexType>
                                             <xs:sequence>
                                                 <xs:element name="genre" type="xs:ID" minOccurs="1" maxOccurs="unbounded"/>
                                             </xs:sequence>
                                         </xs:complexType>
                                     </xs:element>
                                     <xs:element name="kategorien" maxOccurs="1" minOccurs="1">
                                         <xs:complexType>
                                             <xs:sequence>
                                                 <xs:element name="kategorie" type="xs:ID" minOccurs="1" maxOccurs="unbounded"/>
                                             </xs:sequence>
                                         </xs:complexType>
                                     </xs:element>
                                 </xs:sequence> 
                                 <xs:attribute name="bewertung" use="optional" default="0">
                                     <xs:simpleType>
                                         <xs:restriction base="xs:integer">
                                             <xs:minInclusive value="0"/>
                                             <xs:maxInclusive value="5"/>
                                         </xs:restriction>
                                     </xs:simpleType>
                                 </xs:attribute>
                                 <xs:attribute name="theme_id" type="xs:ID" use="required"/>
                             </xs:complexType>
                             
                         </xs:element>
                         <xs:element name="module" minOccurs="1" maxOccurs="1">
                             <xs:complexType>
                                 <xs:all>
                                     <xs:element name="dekoration"  minOccurs="1" maxOccurs="1">
                                         <xs:complexType>
                                             <xs:sequence>
                                                 <xs:element name="dekoration_element" type="beschreibung" minOccurs="0" maxOccurs="unbounded"/>
                                             </xs:sequence>
                                         </xs:complexType>
                                     </xs:element>
                                     <xs:element name="outfits" minOccurs="1" maxOccurs="1">
                                         <xs:complexType>
                                             <xs:sequence>
                                                 <xs:element name="outfit" type="beschreibung" minOccurs="0" maxOccurs="unbounded"/>
                                             </xs:sequence>
                                         </xs:complexType>
                                     </xs:element>        
                                     <xs:element name="musik" minOccurs="1" maxOccurs="1">
                                         <xs:complexType>
                                             <xs:sequence>
                                                 <xs:element name="song" minOccurs="0" maxOccurs="unbounded">
                                                     <xs:complexType>
                                                         <xs:all>
                                                             <xs:element name="song_titel" maxOccurs="1" minOccurs="1"/>
                                                             <xs:element name="song_interpret" minOccurs="1" maxOccurs="1"/>
                                                             <xs:element name="link" minOccurs="0" maxOccurs="1"/>
                                                         </xs:all>
                                                     </xs:complexType>
                                                 </xs:element>
                                             </xs:sequence>
                                         </xs:complexType>
                                     </xs:element>
                                     <xs:element name="catering" maxOccurs="1" minOccurs="1">
                                         <xs:complexType>
                                             <xs:sequence>
                                                 <xs:choice>
                                                     <xs:element name="getraenk" type="rezept" minOccurs="0" maxOccurs="unbounded"/>
                                                     <xs:element name="gericht" type="rezept" minOccurs="0" maxOccurs="unbounded"/>
                                                 </xs:choice>
                                             </xs:sequence>
                                         </xs:complexType>
                                     </xs:element>
                                     <xs:element name="locations" minOccurs="1" maxOccurs="1">
                                         <xs:complexType>
                                             <xs:sequence>
                                                 <xs:element name="location" type="beschreibung" minOccurs="0" maxOccurs="unbounded"/>
                                             </xs:sequence>
                                         </xs:complexType>
                                     </xs:element> 
                                 </xs:all>
                             </xs:complexType>
                         </xs:element>
                         <xs:element name="interaktion" minOccurs="1" maxOccurs="1">
                             <xs:complexType>
                                 <xs:sequence>
                                     <xs:element name="abonennten" maxOccurs="1" minOccurs="1">
                                         <xs:complexType>
                                             <xs:sequence>
                                                 <xs:element ref="user" minOccurs="0" maxOccurs="unbounded"/>
                                             </xs:sequence>
                                         </xs:complexType>
                                     </xs:element>
                                     <xs:element name="kommentare" minOccurs="1" maxOccurs="1">
                                         <xs:complexType>
                                             <xs:sequence>
                                                 <xs:element name="kommentar" minOccurs="0" maxOccurs="unbounded">
                                                     <xs:complexType>
                                                         <xs:sequence>
                                                             <xs:element name="nachricht" type="xs:string" minOccurs="1" maxOccurs="1"/>
                                                             <xs:element ref="user" maxOccurs="1" minOccurs="1"/>
                                                             <xs:element name="uhrzeit" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
                                                         </xs:sequence>
                                                     </xs:complexType>
                                                 </xs:element>               
                                             </xs:sequence>
                                         </xs:complexType>
                                     </xs:element>   
                                 </xs:sequence>
                             </xs:complexType>
                         </xs:element>
                     </xs:sequence>
                 </xs:complexType>
             </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

    <!-- Ausgelagerte Elemente -->
    
    <xs:complexType name="rezept">
        <xs:sequence>
            <xs:element name="rezeptname" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="rezept_link" type="xs:anyURI" maxOccurs="1" minOccurs="1"/> <!-- Es werden nicht direkt Rezepte aufgelistet, sondern nur Linkszu guten Rezepten -->
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="beschreibung">
        <xs:sequence>
            <xs:element name="titel" minOccurs="1" maxOccurs="1"/>
            <xs:element name="bild" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="beschreibung" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="schritt" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="user" type="xs:string"/>
    
</xs:schema>

=== ndang/wba2_phase2/Phase2/XSD/themes.xml
<?xml version="1.0" encoding="UTF-8"?>
<themes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/Ngoc-Anh/Dropbox/FH/4.%20Semester/WBA2/Phase2/XSD/theme.xsd">
    <theme>
        <allgemeines theme_id="t0" bewertung="5">
            <theme_titel>Robust und Glitzernd</theme_titel>
            <genres>
                <genre>g0</genre>
            </genres>
            <kategorien>
                <kategorie>k0</kategorie>
            </kategorien>
        </allgemeines>
        <module>
            <dekoration>
                <dekoration_element>
                    <titel>Shine bright like a diamond!</titel>
                    <bild>http://www.tolle-dekoration.de/diamanten</bild>
                    <text>
                        <schritt>Silberpapier kaufen.</schritt>
                        <schritt>Mit Hilfe der Schablone Diamanten zeichen und ausschneiden.</schritt>
                        <schritt>Die ausgeschnitteten Diamanten an einer Schnur auffädeln.</schritt>
                    </text>
                </dekoration_element>
            </dekoration>
            <outfits>
                <outfit>
                    <titel>The girl's best friend</titel>
                    <bild>http://www.kleider.der/glitzer</bild>
                    <text>
                        <schritt>Dieses Kleid ist einzigartig. Man kann es bei pearliné boutique kaufen.</schritt>
                    </text>
                </outfit>
            </outfits>
            <musik>
                <song>
                    <song_titel>Shine bright like a diamond</song_titel>
                    <song_interpret>Rihanna</song_interpret>
                    <link>http://www.youtubed.de</link>
                </song>
                <song>
                    <song_titel>The girls best friend</song_titel>
                    <song_interpret></song_interpret>
                    <link>http://www.youtubed.de</link>
                </song>
            </musik>
            <catering>
                <gericht>
                    <rezeptname>Perlige Hochzeits-Torte</rezeptname>
                    <rezept_link>http://www.chefkoch.de</rezept_link>
                </gericht>
            </catering>
            <locations>
                <location>
                    <titel>Disneys Schloss</titel>
                    <bild>http://www.disneyland.de</bild>
                    <text>
                        <schritt>Für alle Prinzessinen.</schritt>
                    </text>
                </location>
            </locations>
        </module>
        <interaktion>
            <abonennten>
                <user>pearline</user>
                <user>pearlina</user>
                <user>CrackX</user>
                <user>RaverShawn</user>
                <user>lorainia</user>
                <user>Jorge Henrique Feraira Peraira</user>
                <user>Mama</user>
            </abonennten>
            <kommentare>
                <kommentar>
                    <nachricht>Dieses Kleid steht mir bestimmt super.</nachricht>
                    <user>Zyra</user>
                    <uhrzeit>2013-04-11T20:57:42.998+02:00</uhrzeit>
                </kommentar>
                <kommentar>
                    <nachricht>Wow!</nachricht>
                    <user>Nami</user>
                    <uhrzeit>2013-04-11T20:57:42.998+02:00</uhrzeit>
                </kommentar>
            </kommentare>
        </interaktion>
    </theme>
</themes>
